### ISSUE TITLE
bump rubocop version to 1.9.1

### ISSUE THREAD

**Issue by tbugfinder** [mattlqx/pre-commit-ruby#13]
https://github.com/mattlqx/pre-commit-ruby/blob/e9a0264123e305689935f483819b401702a3e0e2/Gemfile#L5

Kindly update the rubocop version as it includes many bugfixes.

**Comment by mattlqx** [comment]
That's just the version for running against this actual repo. The version of rubocop that pre-commit will run with this plugin is determined by the Gemfile in that repository.

**Comment by tbugfinder** [comment]
Thank you, found the issue on my configuration.
